### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Benjamin-Dobell** [rphlmr/supa-fly-stack#50]
Just noticed `CC BY-NC-SA 4.0` tacked on down the bottom of the README. A copyleft non-commercial license seems highly unusual for a template, however it's your project so absolutely at your discretion. 

That said, could you please add a `LICENSE` file so that Github prominently displays the license?

**Comment by rphlmr** [comment]
Hello @Benjamin-Dobell 

You are right, I've just pushed the target license I wanted for this repo ;) (still working on v2)

**Comment by Benjamin-Dobell** [comment]
Very much appreciated! I'll be interested to see what direction you take. I've already migrated to v2, but it does beg the question as to whether Prisma is even worth it anymore now that Supabase is typed 🤔

**Comment by rphlmr** [comment]
I was thinking of providing the 2 ways (needing Prisma for my daily job).

I played with the new supabase SDK but generating types from here requires supabase-CLI, docker, etc ... too heavy compared to Prisma (which also supports transactions, another prerequisite for me).
It would require installing all of this first. (I know a lot of dev that are lost when we start speaking about Docker, or have low-end computer / Windows OS that should enable Hyper-V / Bios virtualization first)

This is why I create [create-supabase-app](https://github.com/rphlmr/create-supabase-app) during Supabae Hackathon.

Maybe this stack shouldn't do everything, but I have use cases to simultaneously use Prisma and Supabase (client side) (real-time event triggering à Remix loader to refresh).

First step: upgrade and refactor, including "how to remove what I don't want".

Since I already have [a template for a pure Supabase stack](https://github.com/rphlmr/create-supabase-app/tree/main/templates/remix/basic-v2), maybe I can make one without Prisma if nobody did It.
